### ISSUE TITLE
eks-blueprint: Support for using digest in Helm provider

### ISSUE THREAD

**Issue by antmakedev** [aws-quickstart/cdk-eks-blueprints#1120]
### Describe the bug

We are wanting to use helm digest's instead of just using a tag when using helm charts along with the EKS blueprints to raise the security bar. The [CDK docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.HelmChart.html) don't seem to mention using the digest at all and in the blueprints we seem to have [limited the version](https://github.com/aws-quickstart/cdk-eks-blueprints/pull/424/files#diff-09112d191f495f463282eeb1ce6dc7a0bd0bae8cc93537ac04138b28a7fbe976R45) (along with the name that has to be limited) to only 63 characters which doesn't support the length of the sha256 hash. The helm issue mentioned only seems to reference the name value being 63 characters due to DNS reasons not the version.

### Expected Behavior

Expect to be able to reference the helm chart by its sha256 digest

```
image:
  registry: quay.io
  repository: myco/foo
  version: sha256:d478cd82cb6a604e3a27383daf93637326d402570b2f3bec835d1f84c9ed0acc
```

### Current Behavior

Currently you are only able to specify it by value:
```
image:
  registry: quay.io
  repository: myco/foo
  version: 1.0.0
```

### Reproduction Steps

https://github.com/shapirov103/eks-blueprints-extension/blob/main/lib/index.ts

### Possible Solution

Increase the limit of the constraints on the value within HelmAddonPropsConstraints

https://github.com/aws-quickstart/cdk-eks-blueprints/blob/be9ec2d0908df52e9ab570cea34e57ef72353d03/lib/addons/helm-addon/index.ts#L46

### CDK CLI Version

NA

### Node.js Version

NA

### Environment details (OS name and version, etc.)

NA
