### ISSUE TITLE
KarpenterAddOn support for AMI Family

### ISSUE THREAD

**Issue by rstrazza** [aws-quickstart/cdk-eks-blueprints#412]
### Describe the feature

Configure the `KarpenterAddOn` using `'amiFamily': 'Bottlerocket'` like described in the [aws karpenter provisioner example](https://github.com/aws/karpenter/blob/main/examples/provisioner/bottlerocket.yaml):

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  provider:
    amiFamily: Bottlerocket
    subnetSelector:
      karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
    securityGroupSelector:
      karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
```

After looking at the [quistart addon documentation](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/karpenter/) and the [code](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/8415bcb/lib/addons/karpenter/index.ts#L145) it's my impression that the cdk-eks-blueprints does not support this configuration, but I'm new to it and might be missing something obvious.

### Use Case

Provisioning a `MngClusterProvider` using `amiType: NodegroupAmiType.BOTTLEROCKET_X86_64` and would also like to configure the `KarpenterAddOn` to use `amiFamily: Bottlerocket`

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.25.0 (build ae1cb4b)

### Node.js Version

v18.2.0

### Environment details (OS name and version, etc.)

macOS Monterey
