### ISSUE TITLE
 (feat: addons Karpenter) requirements incorrectly Modelled and/or named.

### ISSUE THREAD

**Issue by javydekoning** [aws-quickstart/cdk-eks-blueprints#487]
### Describe the feature

In Karpenter yaml:

```
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.large", "m5.2xlarge"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-west-2a", "us-west-2b"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64"]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["spot", "on-demand"]
```

In EKS Blueprints:

```ts
    provisionerSpecs?: {
        'node.kubernetes.io/instance-type'?: string[],
        'topology.kubernetes.io/zone'?: string[],
        'kubernetes.io/arch'?: string[],
        'karpenter.sh/capacity-type'?: string[],
    }
```

We use the correct naming for `taints`, therefore I think we should rename `provisionerSpecs` to `requirements`. Also, we should remodel this and not hardcode to the `in` operator here: https://github.com/aws-quickstart/cdk-eks-blueprints/blob/f7fba04f2488556366779e56ebb88d860747aa5a/lib/addons/karpenter/index.ts#L180 

### Use Case

Customers might want to use other `operators` or `keys`. 

### Proposed Solution

- rename (this will be a breaking change!)
- remodel so users can use key, operator and values.

Below are some options (pseudo code):

```ts
requirements?: [{
    key: string, 
    operator: "In" | "NotIn" ,
    values: string[],
}]
```

The key itself could be an enum like:

```ts
enum Karpenter.Requirement {
  InstanceType = "node.kubernetes.io/instance-type",
  Zone = "topology.kubernetes.io/zone",
  Arch = "kubernetes.io/arch",
  CapacityType = "karpenter.sh/capacity-type",
}
```

We could also model the requirements into a It's own class. That way, we can use TS to do type-checking and leverage:

- `@aws-cdk/aws-ec2 » InstanceType`
- Default zones to `cdk.Stack.of(this).availabilityZones`
- `@aws-cdk/aws-ec2 » InstanceArchitecture`
- CapacityType

Something like:

```
export interface RequirementOpts {
  operator: "In" | "NotIn" ,
}

export interface InstanceType extends RequirementOpts {
  values: ec2.InstanceType[] ,
}

export interface Requirements {
  InstanceType: InstanceType;
  Zone: xxx;
}
```

### Acknowledgements

- [x] I may be able to implement this feature request

### CDK version used

N/A

### EKS Blueprints Version

1.2.0

### Node.js Version

N/A

### Environment details (OS name and version, etc.)

N/A
