### ISSUE TITLE
external-dns: Not filtering to provided HostedZoneID's

### ISSUE THREAD

**Issue by DanielAtanasovski** [aws-quickstart/cdk-eks-blueprints#791]
### Describe the bug

Since [this change](https://github.com/aws-quickstart/cdk-eks-blueprints/pull/739) from the `Bitnami` to the `kubernetes-sigs` helm chart, provided HostedZones are not being filtered to and passed as args to the `external-dns` container like previously.

### Expected Behavior

Previous generated container args:

```YAML
      containers:
        - name: external-dns
          image: docker.io/bitnami/external-dns:0.13.4-debian-11-r14
          imagePullPolicy: "IfNotPresent"
          args:
            # Generic arguments
            - --metrics-address=:7979
            - --log-level=info
            - --log-format=text
            - --zone-id-filter=XXXXXXXXXX
            - --policy=upsert-only
            - --provider=aws
            - --registry=txt
            - --interval=1m
            - --source=service
            - --source=ingress
            # AWS arguments
            - --aws-api-retries=3
            - --aws-zone-type=
            - --aws-batch-change-size=1000
```

### Current Behavior

Current container args:

```YAML
          image: registry.k8s.io/external-dns/external-dns:v0.13.5
          imagePullPolicy: IfNotPresent
          args:
            - --log-level=info
            - --log-format=text
            - --interval=1m
            - --source=service
            - --source=ingress
            - --policy=upsert-only
            - --registry=txt
            - --provider=aws
          ports:
```

Resulting in errors where it fails to list records in an unrelated zone in the same account:
```
level=fatal msg="failed to list resource records sets for zone /hostedzone/SOME_OTHER_ZONE: AccessDenied: User: arn:aws:sts::ACCOUNTID:assumed-role/CLUSTER_ROLE/ is not authorized to perform: route53:ListResourceRecordSets on resource: arn:aws:route53:::hostedzone/SOME_OTHER_ZONE because no identity-based policy allows the route53:ListResourceRecordSets action\n\tstatus code: 403,"
```

### Reproduction Steps

Deploy a cluster with the external-dns addon and pass in the hostedzone from the resource provider.

```TYPESCRIPT

const hostedZoneName = some-zone

const addOn = new blueprints.addons.ExternalDnsAddOn({
    hostedZoneResources: [hostedZoneName]; // can be multiple
});

const blueprint = blueprints.EksBlueprint.builder()
  .addOns(addOn)
  .resourceProvider(hostedZoneName, new blueprints.LookupHostedZoneProvider(hostedZoneName))
  .addOns(addOn)
  .build(app, 'my-stack-name');

```

### Possible Solution

[`extraArgs` is a property ](https://github.com/kubernetes-sigs/external-dns/tree/master/charts/external-dns#configuration)where the expected outcome can probably be recreated by manually inserting the `zone-id-filter` arg.

### Additional Information/Context

There doesn't exist a [`zoneIdFilters`](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/external-dns/index.ts#L83) property now like there was previously with the `Bitnami` helm chart, but that's still passed in.

### CDK CLI Version

2.86.0

### EKS Blueprints Version

1.10.1

### Node.js Version

18.16.1

### Environment details (OS name and version, etc.)

AWS EKS v1.26
