### ISSUE TITLE
AMP Collector Config needs to be Upgrade for AMP Addon

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#863]
### Describe the feature

Amp Connector [Config](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/amp/collector-config-amp.ytpl) needs following update. 

```yaml
  image: public.ecr.aws/aws-observability/aws-otel-collector:v0.33.1
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "2Gi"
```

### Use Case

Upgrade AMP Collector Config.

### Proposed Solution

Amp Connector [Config](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/lib/addons/amp/collector-config-amp.ytpl) needs following update. 

```yaml
  image: public.ecr.aws/aws-observability/aws-otel-collector:v0.33.1
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "2Gi"
```

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.99.0

### EKS Blueprints Version

1.12.0

### Node.js Version

20.0.0

### Environment details (OS name and version, etc.)

Mac
